### ISSUE TITLE
Running example on Raspbian/Raspberry

### ISSUE THREAD

**Issue by vinifr** [githubuser0xFFFF/QtFreeVirtualKeyboard#3]
Hi, I cross compiled QT 5.5.1 and QtFreeVirtualKeyboard for Raspberry PI 2.

I copied manually the .qml files for /usr/local/qt5pi/qml/QtQuick/VirtualKeyboard and libVirtualKeyboard.so for /usr/local/qt5pi/plugins/platforminputcontexts/
But when I try to execute, return:
<sub>
./virtualkeyboardqmldemo 
VirtualKeyboardInputContextPlugin::create:  "qtvirtualkeyboard"
[9;0]Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
file:///home/pi/projs/QtFreeVirtualKeyboard/examples/qmlapp/MainContainer.qml:20:1: module "QtQuick.VirtualKeyboard" is not installed 
     import QtQuick.VirtualKeyboard 1.0 
     ^
VirtualKeyboardInputContext::setFocusObject</sub>

**Comment by vinifr** [comment]
Nevermind, I just copied qlmdir and worked fine! Thanks for your great work!

**Comment by nemethati10** [comment]
Where did you copy qmldir? (in which directory) Have you done anything else?

**Comment by vinifr** [comment]
First of all, I did cross compile Qt5 for Raspberry: [http://exploreembedded.tumblr.com/post/115333857238/guide-to-cross-compile-qt-54-for-the-raspberry-pi](url), but i'm not sure if we can use QT5 from Ubuntu.  Has Ubuntu enabled hard acceleration on Qt5? You have to check out.

Also, I did change _import VirtualKeyboard 1.0_ to _import QtQuick.VirtualKeyboard 1.0_, inside InputPanel.qml and KeyButton.qml.

After that, copy the files to file system of Raspberry, where you did install QT5(cross compiled or Ubuntu version). In my case(QT5 cross compiled):
*.qml ---> /usr/local/qt5pi/qml/QtQuick/VirtualKeyboard
libVirtualKeyboard.so --> /usr/local/qt5pi/plugins/platforminputcontexts

 That is all.

**Comment by bahaeddine93** [comment]
@vinifr hello, I cross compiled QT 5.5.0 for Raspberry pi 2 and Now i don't know how to do this for the project "QtFreeVirtualKeyboard" to make it run on my Raspberry pi.

**Comment by vinifr** [comment]
@bahaeddine93 hi. You have to configure QT Creator in your PC. Look in section "Setting up Qt Creator" from "https://exploreembedded.tumblr.com/post/115333857238/guide-to-cross-compile-qt-54-for-the-raspberry-pi". After configure QT Creator, open virtualkeyboard.pro, choice Raspberry target created in Kits and compile.

**Comment by bahaeddine93** [comment]
I followed this tutorial "https://visualgdb.com/tutorials/raspberry/qt/embedded/" to cross compile QT5.5.0 for raspberry but when I came to deployment (hello world app) I get this error "Unknown module(s) in QT: qml quick". How can I fix this?
